# Generated by Django 3.0.5 on 2020-04-13 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_type', models.CharField(max_length=10)),
                ('location_type', models.CharField(max_length=45)),
                ('street', models.CharField(max_length=45)),
                ('xstreet1', models.CharField(max_length=45)),
                ('xstreet2', models.CharField(max_length=45)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_cord', models.FloatField()),
                ('y_cord', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('contact', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MapQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=45)),
                ('origin_lat', models.FloatField()),
                ('origin_lng', models.FloatField()),
                ('destination', models.CharField(max_length=45)),
                ('destination_lat', models.FloatField()),
                ('destination_lng', models.FloatField()),
                ('polyline', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Streetlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PolyHospitalProximity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference', models.FloatField()),
                ('hospital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bike.Hospital')),
                ('query', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bike.MapQueries')),
            ],
        ),
        migrations.CreateModel(
            name='PolyAccidentProximity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference', models.FloatField()),
                ('accident', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bike.AccidentPoint')),
                ('query', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bike.MapQueries')),
            ],
        ),
        migrations.CreateModel(
            name='Poly_Streetlight_Proximity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference', models.FloatField()),
                ('query', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bike.MapQueries')),
                ('streetlight', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bike.Streetlight')),
            ],
        ),
    ]
