git# Generated by Django 3.0.5 on 2020-04-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapqueries',
            name='name',
            field=models.CharField(default='Route', max_length=255),
        ),
    ]
