# Generated by Django 3.0.5 on 2020-04-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_auto_20200413_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poly_streetlight_proximity',
            name='difference',
        ),
        migrations.RemoveField(
            model_name='polyaccidentproximity',
            name='difference',
        ),
        migrations.RemoveField(
            model_name='polyhospitalproximity',
            name='difference',
        ),
    ]
