# Generated by Django 3.0.5 on 2020-04-15 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_auto_20200414_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accidentCount', models.IntegerField()),
                ('hospitalCount', models.IntegerField()),
                ('streetlightCount', models.IntegerField()),
                ('query', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bike.MapQueries')),
            ],
        ),
    ]
